tax_payer_number: "Tax number"
tax_payer_type: "FO"
document_workflow_id: "0"
name: "FULL NAME"
city: "CIRT"
address1: "ADDRESS 001"
post_name: "POST NAME"
post_number: "1000"
payer_name: "Payer name"
payer_address: "Payer address"
payer_country: "NL"
type: "3"
source_country: "IE"
foreign_tax_percent: 25
relief_statement: "mp. št 25/02, drugi odstavek, 10. člen"
